fix database checking due to new feature in Express where database named OPENSHIFT_APP_NAME is automatically created

diff --git a/.openshift/action_hooks/build b/.openshift/action_hooks/build
--- a/.openshift/action_hooks/build
+++ b/.openshift/action_hooks/build
@@ -16,13 +16,12 @@ then
 fi
 
 # Confirm database exists, if not create it
-if ! /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -e "show tables;" drupal > /dev/null
+if ! /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" -e "select * from actions;" "$OPENSHIFT_APP_NAME" > /dev/null
 then
     echo
-    echo "Database not found!  Creating and importing"
+    echo "Database schema not found, importing 'drupal.sql' schema."
     echo
-    /usr/bin/mysqladmin -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" create "drupal"
-    /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" drupal < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/drupal.sql"
+    /usr/bin/mysql -u "$OPENSHIFT_DB_USERNAME" --password="$OPENSHIFT_DB_PASSWORD" -h "$OPENSHIFT_DB_HOST" "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/drupal.sql"
     echo
     echo "done."
     echo "=================================================="
